Create pfc_chayka.ini
ac-custom-shaders-patch/acc-extension-config pull request #101
Opened 2021-03-09 10:51 UTC by den-88fish

My first experience here on hosting configs. Tips and tricks are appreciated.

2021-03-09 15:44 UTC, den-88fish commented on config/tracks/pfc_chayka.ini
> +SHADER = ;ksGrass
replacing the shader will help me get rid of the dark border in gravel

2021-03-09 19:07 UTC, RustyChest requested changes

2021-03-09 19:07 UTC, RustyChest commented on config/tracks/pfc_chayka.ini
> +SHADER = ;ksGrass
Sure but once again, you're not actually doing anything?
The ```SHADER=``` parameter is to change the actual shader used, not the parameters
It is only to be specified when you're changing it from one shader to another

2021-03-10 16:40 UTC, den-88fish commented on config/tracks/pfc_chayka.ini
> +ACTIVE = 1
> Active isn't needed
It turns out that it is necessary. After I removed this, the whole texture began to glow for me.when i leave ACTIVE = 1 then the areas that I have identified are illuminated

2021-03-16 16:17 UTC, RustyChest commented
This PR is obsolete as there was an update to the config, now making it incompatible. Hope the pointers helped at the very least

2021-03-16 16:17 UTC, closed without merging